name: base tests

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: compile
      id: build
      run: make -j4 dep; make -j4 push_swap; make SILENT=1 PRINTSTACK=1 -j4 checker; make ft_checker
      continue-on-error: false

    - name: duplicate numbers
      id: dupe
      run: ./push_swap 1 2 3 2 4 5 -2 | ./checker 1 2 3 2 4 5 -2
      continue-on-error: true
      
    - name: check error & mark success
      run: exit 0
      continue-on-error: true

    - name: check illegal input
      id: illegal1
      run: ./push_swap 1 2 3 15s6 4 5 -2 | ./checker 1 2 3 15s6 4 5 -2
      continue-on-error: true
      
    - name: check error & mark success
      run: exit 0
      continue-on-error: true

    - name: check illegal input
      id: illegal2
      run: ./push_swap 1 2 3 +15s6 4 5 -2 | ./checker 1 2 3 +15s6 4 5 -2
      continue-on-error: true
      
    - name: check error & mark success
      run: exit 0
      continue-on-error: true

    - name: check illegal input
      id: illegal3
      run: ./push_swap 1 2 3 -15s6 4 5 -2 | ./checker 1 2 3 -15s6 4 5 -2
      continue-on-error: true
      
    - name: check error & mark success
      run: exit 0
      continue-on-error: true

    - name: check illegal input
      id: illegal4
      run: ./push_swap 1 2 3 15-6 4 5 -2 | ./checker 1 2 3 15-6 4 5 -2
      continue-on-error: true
      
    - name: check error & mark success
      run: exit 0
      continue-on-error: true

    - name: check int max
      id: intmax
      run: ./push_swap 1 2 3 2147483648 4 5 -2 | ./checker 1 2 3 2147483648 4 5 -2
      continue-on-error: true
      
    - name: check error & mark success
      run: exit 0
      continue-on-error: true

    - name: check int min
      id: intmin
      run: ./push_swap 1 2 3 -2147483649 4 5 -2 | ./checker 1 2 3 -2147483649 4 5 -2
      continue-on-error: true
      
    - name: check error & mark success
      run: exit 0
      continue-on-error: true

    - name: check long long max
      id: llmax
      run: ./push_swap 1 2 3 9223372036854775808 4 5 -2 | ./checker 1 2 3 9223372036854775808 4 5 -2
      continue-on-error: true
      
    - name: check error & mark success
      run: exit 0
      continue-on-error: true

    - name: check long long min
      id: llmin
      run: ./push_swap 1 2 3 -9223372036854775809 4 5 -2 | ./checker 1 2 3 -9223372036854775809 4 5 -2
      continue-on-error: true
      
    - name: check error & mark success
      run: exit 0
      continue-on-error: true
